# Generated by Django 4.2.20 on 2025-03-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='size',
            field=models.CharField(choices=[('0', 'Small'), ('1', 'Medium'), ('2', 'Large'), ('3', 'Extra Large')], default='1', max_length=1),
        ),
    ]
